### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by flyingfrog81** [ska-telescope/C_DFT#4]
Just want to point out that we have licensing guidelines at: http://developer.skatelescope.org/en/latest/projects/licensing.html 

If it is not a great deal for you, I'd appreciate if you could swap the license to BSD-3-CLAUSE, this helps in making things easier to maintain.

**Comment by adamrcampbell** [comment]
Hi Marco,

Apologies, this has now been corrected to the BSD-3-clause license.

Regards,
Adam
